config/routes.rb
WatermelonBust::Application.routes.draw do
  resources :pins

  root "pages#home"
  get "about" => "pages#about"
  get "media" => "pages#media"
  get "walmart" => "pages#walmart"
  
end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

	def about 
	end 

	def media
	end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      
      params.require(:pin).permit(:description, :image)
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="https://www.linkedin.com/pub/zach-blass/52/438/796">Zach Blass</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Resume", about_path %></li>
      <li><%= link_to "Media/Press/Reel", media_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zach Blass</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

		<%= render 'layouts/header' %>
     <div class="container">
          <%= yield %>
     </div>


</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron center">
<img src="https://scontent-lga1-1.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/382748_10150939284245538_236987618_n.jpg?oh=79a7276ad54500ec41d5ceb568ae1cc7&oe=56243AF3" alt="Hello There" width="device-width" height="device-height">
<h3>Zachary B. Blass</h3>	
<h4>12 East 86th Street • New York, NY 10028 • 917.589.5070 • zachary.blass@gmail.com</h4>
<h5> University of Maryland, College Park, MD • Bachelor of Arts, English • Minor in Rhetoric • Anticipated May 2016</h5>                                              

<h4>Social Media Strategist: BrandShare</h4>
<h5>Novemeber 2014 - Present</h5>
<h6>• (Will)Continue to develop/finalize/finetune Social Sharing Program</h6>
<h6>• (Will)Develop Growth Hacking Tactics to encourage more traffic to our various subscription boxes/offers/domains</h6>
<h6>• (Will)Maintain/Supervise Simply Measured Data Sources/Collections. Collected data will convey the efficacy of our campaigns, reports will become a tool for renewals</h6>
<h6>• (WIll)Analyze survey and social data for relevant consumer and subscriber trends. Customer Profile/Analysis.</h6>
<h6>• (Will)Collaborate on Social Sharing Campaigns with AM/AE to create & execute Social Sharing Methodology as well as execute new and creative ideas for effective social campaigns that encourage further renewals</h6>
<h6>• (Will)Provide direction/copy for WMBOX sites</h6>	
<h6>• (Will)Manage Qr Generator, and corresponding analysis</h6>
<h6>• (Will)Navigate Google Analytics for any relevant website metrics</h6>
<h6>• (Will)Research innovative ways our Brands and Marketing Firms (respectively) markets to our common consumers, and evaluate how to incorporate as appropriate for BrandShare</h6>
<h6>• (Will)Delve into previous campaigns, and note effective tactics that trended in effective campaigns.</h6>
<h1> </h1>
<h1> </h1>
<h4>Junior Agent: Best Apartments NYC, New York, NY</h4>                          
<h5>June 2014 - August 2014</h5>
<h6>• Created online advertisements/listings for apartment rentals all throughout New Yorck City (i.e postles, zillow, nakedapartments, etc.)</h6>
<h6>• Showed prospective renters the apartments, acted as a guide as the apartments were toured.</h6>
<h6>• Worked/Communicated with clients and building managers to create an optimal renting experience for all parties involved.</h6>
<h6>• Photographed apartments for listings</h6>
<h1> </h1>
<h1> </h1>
<h4>VP of External Relations: Lambda Chi Alpha (Epsilon-Pi) Fraternity, UMD – College Park </h4>                                                         
<h5>September 2013 – December 2013</h5>
<h6>• Organized National Philanthropy, Watermelon Bust! In service to Feeding America</h6>
<h6>• Coordinated with other Greek and Non-Greek organizations to acquire participants for in-house events as well as co-sponsor the events of our student peers.</h6>
<h6>• Maintained budget.</h6>
<h6>• Held weekly committee meetings to delegate and complete operations.</h6> 
<h1> </h1>
<h1> </h1>
<h4>Media Buyer: BrandReach, New York, NY</h4>                                       
<h5>May 2013 - August 2013</h5>
<h6>• Optimized advertising campaigns to obtain maximum traffic/membership joins with minimum costs</h6>
<h6>• Conducted research analysis using excel, and Compete (CPA, eCPM, CPM, and more).</h6>
<h6>• Directed banner designers to meet marketing strategy.</h6>
<h6>• Managed auctions and recruited new clients</h6>
<h6>• Organized data in a logical and clearly communicated manner</h6>
<h6>• Presented weekly reports to evaluate ad-buys and their respective metrics.</h6>
<h1> </h1>
<h1> </h1>
<h4>Media & Marketing Strategist: EatDrinkJobs, New York, NY </h4>                  
<h5>May 2012 - July 2012</h5>
<h6>• Worked with Google Analytics to give insight into web traffic</h6>
<h6>• Assisted in managing the company’s Facebook, Twitter, and Blog</h6>
<h6>• Article I wrote on “Food Truck Craze” was retweeted by the NYC Food Truck Association.</h6>
<h6>• Strategically acquired traffic, likes, and followers.</h6>
<h6>• Start-up business experience, helped grow a young business.</h6>
<h1> </h1>
<h1> </h1>
<h4>Day Camp Counselor: Camp Yomi (92nd Street Y), Rockland County, NY </h4>
<h5>Summers 2009 - 2011</h5>
<h6>• Oversaw groups of 15-20 five and six year olds.</h6>
<h6>• Interacted/Collaborated with directors and staff, and parents to produce quality teamwork, open communication, and appropriate troubleshooting.</h6>
<h6>• Assisted in planned daily activities (i.e Swim, Basketball, Baseball).</h6>
<h6>• Improvised and created activities in Free-Time or in inclement weather to keep morale and entertainment up for the campers.</h6>
<h6>• Camp-Yomi Olympics General. (Only 4 counselors in unit are chosen).</h6>
<h1> </h1>
<h1> </h1>
<h4>**COMPUTER SKILLS**</h4>
<h6>• Proficient in Excel, PowerPoint, Word.</h6>
<h6>• Basic Understanding of Ruby</h6>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
<img src="https://scontent-lga1-1.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/382748_10150939284245538_236987618_n.jpg?oh=79a7276ad54500ec41d5ceb568ae1cc7&oe=56243AF3" height="device-height">
<h1>Hello There!</h1>
<h4>Welcome to Zach's Online Portfolio/Resume</h4>
<p>Click <%= link_to "here", "https://www.linkedin.com/pub/zach-blass/52/438/796" %> to visit Zach's LinkedIn page!</p>

app/views/pages/media.html.erb
<div class="jumbotron left">

	<h3>Teen Kids News Reporting</h3>

<iframe width="560" height="315" src="//www.youtube.com/embed/k2FmTv8us-M?list=UUifUdOrX9_IwG5ORJ-MNAzg" frameborder="0" allowfullscreen></iframe>

</div>

<div class="jumbotron left">
	<h3>An article I wrote on the topic of Food Trucks in NYC for the EatDrinkJobs Blog, which was later Retweeted by the NYC Food Truck Association</h3>
<p> <%= link_to "Meals on Wheels: An Intern’s Take on the Food Truck Craze", "http://www.eatdrinkjobs.com/blog/2012/08/07/meals-on-wheels-an-interns-take-on-the-food-truck-craze/" %> </p>
	<img src="https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xpa1/t1.0-9/10570389_10154287088100538_1412597937382836097_n.jpg" alt="Blog" width="device-width" height="device-height">
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= image_tag pin.image.url(:medium) %></td>
        <td><%= pin.description %></td>
        <td><%= pin.user.email if pin.user %></td>
        <td><%= link_to 'Show', pin_path(pin) %></td>
        <% if pin.user == current_user %>
          <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
          <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path %>
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= image_tag @pin.image.url(:medium) %>

<p>
  <strong>Description:</strong>
  <%= @pin.image.url(:medium) %>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>